### ISSUE TITLE
Automatic decision of presicion

### ISSUE THREAD

**Issue by csoeger** [Normaliz/Normaliz#10]
libnormaliz should internally decide which integer type it uses for the computations. My suggestion:
The user interface (Cone) then has to be able to deal with large numbers, so it should use gmp.
Cone also uses gmp internally, especially for computing the SublatticeRepresentation.
The Full_Cone is then created with a flexible type. Default would be 64 bit and if it does not work out a bool is set so that we know it doesn't work with 64 bit and restart with gmp. This bool could also be directly activated by some preliminary checks or by the user.

In this setup the library interface could become less templated, e.g. the Cone itself could be non-templated but it might have input/output functions which are templated.

**Comment by csoeger** [comment]
We decided to keep the templated cones.
The cone<mpz_class> will get the possibility to use a smaller integer type internally. So this will be the new general interface. We might make a typedef to it, so the fact that it is templated is hidden to some extend.

For the internal use and as well the convenience for libnormaliz user we will offer general Convert methods for integers, vectors, matrices, ...

**Comment by w-bruns** [comment]
We plan the following strategy: try 64 bit, and if it crashes restart computation with GMP. Requires catching exceptions properly. See issue "Exceptions and threads". (Should be done by now.)

**Comment by csoeger** [comment]
Cone<mpz_class> can now change internally to use long long.
NOT YET used in compute_dual.

Also Normaliz itself should use this feature.

**Comment by csoeger** [comment]
Completed
