### ISSUE TITLE
lintian shlib-calls-exit

### ISSUE THREAD

**Issue by jgmbenoit** [Normaliz/Normaliz#155]
[Lintian](https://lintian.debian.org/) emits a [shlib-calls-exit](https://lintian.debian.org/tags/shlib-calls-exit.html) for the library libnormaliz.
It appears that the library call exit() when it fails to read matrices (s/l/matrix.cpp), so it is not a kind a forgotten debugging codes but rather a design issue. I guess it can be easily remove either by bringing the involved code outside the library or by returning  an appropriate error code.

**Comment by w-bruns** [comment]
Will be replaced by BadInputException.

**Comment by w-bruns** [comment]
Done
