### ISSUE TITLE
Using cone vector error

### ISSUE THREAD

**Issue by akrsnr** [Normaliz/Normaliz#160]
When I want to run the code i get error,

```
#include <libnormaliz/libnormaliz.h>
#include <libnormaliz/cone.h>
#include <vector>

int main() {
    std::vector<std::vector <int> > data { {1,1,1}, {2,2,2} };

    libnormaliz::Type::InputType type = libnormaliz::Type::cone;
    /* runs well up to here */
    libnormaliz::Cone<int> MyCone = libnormaliz::Cone<int>(type, data);

    return 0;
}
```

Undefined symbols for architecture x86_64:
  "libnormaliz::Cone<int>::Cone(libnormaliz::Type::InputType, std::__1::vector<std::__1::vector<int, std::__1::allocator<int> >, std::__1::allocator<std::__1::vector<int, std::__1::allocator<int> > > > const&)", referenced from:
      _main in normaliz.cpp.o
  "libnormaliz::Cone<int>::~Cone()", referenced from:
      _main in normaliz.cpp.o
ld: symbol(s) not found for architecture x86_64

**Comment by w-bruns** [comment]
libnormaliz does not support the type int for cones. It is set up for the following three types:
```
long
long long
mpz_class
```
Try long long instead of int.

**Comment by akrsnr** [comment]
Same error appears for

```
std::vector<std::vector <long long> > data { {1,1,1}, {2,2,2} };

    libnormaliz::Type::InputType type = libnormaliz::Type::cone;
    /* runs well up to here */
    libnormaliz::Cone<long long> MyCone = libnormaliz::Cone<long long>(type, data);
```

**Comment by w-bruns** [comment]
I have no problem after the change from int to long long (using my standard environment):
```
make -f Makefile.classic 
g++ -I .. -std=c++11 -Wall -pedantic -O3 -funroll-loops -g        -fopenmp -static -DNMZ_COCOA -DCoCoA_THREADSAFE_HACK -I /home/winfried/CoCoA/CoCoALib-0.99550/include -o Soner Soner.cpp -L../libnormaliz -lnormaliz  /home/winfried/CoCoA/CoCoALib-0.99550/lib/libcocoa.a -lgmpxx -lgmp
/usr/lib/gcc/x86_64-linux-gnu/5/libgomp.a(target.o): In Funktion `gomp_target_init':
(.text+0xba): Warnung: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
The file Soner.cpp is in a subdirectory of source (like maxsimplex):

```
#include <libnormaliz/libnormaliz.h>
#include <libnormaliz/cone.h>
#include <vector>

int main() {
    std::vector<std::vector <long long> > data { {1,1,1}, {2,2,2} };

    libnormaliz::Type::InputType type = libnormaliz::Type::cone;
    /* runs well up to here */
    libnormaliz::Cone<long long> MyCone = libnormaliz::Cone<long long>(type, data);

    return 0;
}
```
and Makefile.classic is essentially a copy of the corresponding file in maxdimplex
```
##
## Makefile configuration for maxsimplex and others
##

#######  customize  ######

LIBNORMALIZ_DIR = ../libnormaliz
CXXFLAGS += -I ..
MY_PROG = Soner

##### end customize ######

include ../Makefile.configuration

LINKFLAGS = -L$(LIBNORMALIZ_DIR) -lnormaliz
LINKFLAGS += $(SCIPFLAGS) $(COCOAFLAGS) $(GMPFLAGS)

default: $(MY_PROG) 

%: %.cpp ../libnormaliz/libnormaliz.a
	$(CXX) $(CXXFLAGS) -o $@ $< $(LINKFLAGS)

clean:
	rm -f $(MY_PROG) *.o
```

**Comment by akrsnr** [comment]
Thank you for your help, but in our project we try to use libnormalize like that
- open clion,
- import project from source,
- choose source folder in Normalize-master
- build it. It's ok so far.

Then,

I'm adding the command in CmakeLists.txt,

`include_directories(/Users/soner/Documents/Normaliz-master/source)
`

Is the way wrong to use the library? I'm a Clion user and working on it.

Regards,
Soner

**Comment by w-bruns** [comment]
I think it is not a matter of the include directories (where the source files are residing). My first guess is that the linker does not find the compiled library.

**Comment by akrsnr** [comment]
Thanks. I got and solved the problem. The question can be removed if you wish. However, I have another question about cones. I hoped that there is a intersection function to intersect two cones but not. How can I intersect two cones or more cones?

**Comment by w-bruns** [comment]
Since you are programming with libnormaliz, you can write a function of your own. Suppose only the cones are of interest (and not the lattices). Then you compute both cones. The next step is to extract the support hyperplanes and equations from each of them. Now make new matrices by collecting the support hyperplanes in one matrix and the equations in the other. Finally make a new cone from the united support hyperplanes and united equations. 

If lattices are asked for, proceed as above, but additionally use the congruences.

**Comment by akrsnr** [comment]
Umm, but seemingly there is no method to obtain a created cone's inequalities. Is there?

**Comment by w-bruns** [comment]
You can access all the computed data. Please have a look at Section D.4 of the manual.

**Comment by w-bruns** [comment]
All questions answered.
