### ISSUE TITLE
test-/5x5PF test fails on Debian unstable for arm64,  ppc64el, s390x, powerpc and ppc64 architectures

### ISSUE THREAD

**Issue by jgmbenoit** [Normaliz/Normaliz#161]
normaliz 3.4.1 was finally uploaded. As claimed in the title, [here](https://buildd.debian.org/status/package.php?p=normaliz), test-/5x5PF test  fails on Debian unstable for some architectures.
Can you reproduce it on a least one of them ? If not, please let me know what I can do.
Cheers, Jerome

**Comment by w-bruns** [comment]
This is an extremely sensitive test since it uses floating point arithmetic for a system of equations and requires the result to give exact integers. I was surprised that it works at all. I think the only possibility is to remove it.

**Comment by jgmbenoit** [comment]
Is there a way to control the error ? Otherwise, instead of removing the test, it can be kept without taking into account its failure as far as the check is concerned. In short, deterministic tests are required by robots.

**Comment by w-bruns** [comment]
So we leave it as it is.

**Comment by jgmbenoit** [comment]
Ok. From my side, as Debian maintainer, it is not satisfactory. I am on my way to write a patch to neutralize it.

**Comment by w-bruns** [comment]
I am thinking about moving this test to a special directory so that it can only be run at special request.
In fact, the choice of the algorithm ProjectionFloat in this test is unnatural for the task. For me it was an attempt to see how far I can go with floating point arithmetic. 
The natural choices are Projection or DualMode, both using integer arithmetic.

**Comment by jgmbenoit** [comment]
I suspected some kind of numerical experiment. Otherwise, moving this kind of test to a dedicated directory sounds as a good idea.

**Comment by w-bruns** [comment]
5x5PF moved to test-Special
