### ISSUE TITLE
test-nn/medium fails on alpha architecture

### ISSUE THREAD

**Issue by jgmbenoit** [Normaliz/Normaliz#163]
For normaliz 3.4.1 , the test test-nn/medium fails with Debian unstable on alpha architecture; see the [log](https://buildd.debian.org/status/fetch.php?pkg=normaliz&arch=alpha&ver=3.4.1%2Bds-2&stamp=1510943245&raw=0).

**Comment by w-bruns** [comment]
No idea what could be wrong. Did the test pass for 3.1.1?
As a first information I need
1. medium.out
2. the terminal log produced with -c
I will explore whether a DEC alpha (production stopped in 2007) still exists in my neighborhood.

**Comment by jgmbenoit** [comment]
the terminal log produced with -c : can you be more explicit ?

**Comment by w-bruns** [comment]
Assuming that test is our working directory and  the binary notmaliz is in the directory source, run the following command
`../source/normaliz -cN test-nn/medium`
The option -N is used for the tests in test-nn, and -c asks for the terminal log.

**Comment by jgmbenoit** [comment]
It appears that Debian provides no alpha porterbox, in other words I have not access to an alpha computer (and my University is to young to have one of them). So I will try some compiler options used in other packages for alpha boxes at the next upload.

**Comment by w-bruns** [comment]
The next days I will also look in my university for such a machine (or at least an emulation). I know that our physics department had Dec Alpha ~ 15 years ago.

**Comment by jgmbenoit** [comment]
Finally I have access to an Alpha Debian porterbox. So no need to disturb the ghosts of your Physics Dept. . I will have a look this week-end (Friday-Saturday here)

**Comment by jgmbenoit** [comment]
Finally I could reproduce the issue on the Debian Alpha porterbox.
Here are the requested outputs:
[test-nn__medium_log-00.txt](https://github.com/Normaliz/Normaliz/files/1503674/test-nn__medium_log-00.txt)
[test-nn__medium_out-00.txt](https://github.com/Normaliz/Normaliz/files/1503675/test-nn__medium_out-00.txt)

**Comment by w-bruns** [comment]
The difference between out and ref files is
```
< size of partial triangulation   = 23019
< resulting sum of |det|s = 58766
---
> size of partial triangulation   = 23023
> resulting sum of |det|s = 58774
```

This means that the computation of the Hilbert basis (aimed at by this test) is correct. The information on the size of the triangulation and the sum of the determinants is an information for the user showing the complexity of the computation. There can be variations depending on the parallelization. The diff of the log files is
```
< evaluating 23025 simplices
---
> evaluating 23019 simplices
61,62c63,64
< 23025 simplices, 217 HB candidates accumulated.
< Total number of pyramids = 16981, among them simplicial 8720
---
> 23019 simplices, 217 HB candidates accumulated.
> Total number of pyramids = 16977, among them simplicial 8716
```
It shows the same effect. 
I am not sure what one can do at this point.

**Comment by jgmbenoit** [comment]
So it is not architecture related: good news.
What can be done is to write a diff script that do not compare non reproducible number.

**Comment by w-bruns** [comment]
For the time being, let us close this issue.

**Comment by jgmbenoit** [comment]
As an example for a specific diff executable, you can have a look to nauty.

**Comment by w-bruns** [comment]
I will add ignore options to the diff command.

With version 3.5.0 that I am just preparing, the situation is even more complicated. Not all computation results are uniquely determined, and since floating point arithmetic is used as an auxiliary tool, the course of the computation can vary, resulting in varying results. I will try to avoid problems by providing a second ref file.

**Comment by jgmbenoit** [comment]
Can you play with relative errors ?
In this case, the GNU Scientific Library (GSL) library is a better example to give.

**Comment by w-bruns** [comment]
I think I have solved the all the known (!) test problems. The way out of the floating point problem was the transformation of the output to a normal form, even if it does not always look so nice.

**Comment by w-bruns** [comment]
Meanwhile 3.5.0 is the latest official release. I would not mind if it could be tested on Debian systems. I have tried to take care of all problems that have come up.

**Comment by jgmbenoit** [comment]
I may have a look this week-end or the next.
