### ISSUE TITLE
No shift if all generators have degree >= 0

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#20]
We could suppress the shift if all generators live in degree >= 0. This saves transformations of the quasipolynomial.

Note: excluded_faces do not introduce a shift.

**Comment by csoeger** [comment]
We will suppress the shift if it is possible (all generators have non-negative degree).

And in any case we will compute the corrected Hilbert quasi-polynomial. So that the user does not have to make a linear substitution.

**Comment by csoeger** [comment]
The Hilbert series is now always shifted to start in degree 0.
