### ISSUE TITLE
normaliz wont open the example .in file

### ISSUE THREAD

**Issue by geraldmorgan13** [Normaliz/Normaliz#218]
I am completely new to this software and I wanted to use it for my research. I downloaded the latest normaliz 3.6.2 and unzipped the file. I even downloaded the Mac executable and included in the folder that holds all other files in normaliz 3.6.2. Tried to run the example that was included and I get this error:

with package(s) CoCoALib Flint
error: Failed to open file "/Users/geraldmorgan/Desktop/Research Docs/normaliz-3.6 2.3/example/2cone".in.

![Screen Shot 2019-03-17 at 3 56 54 PM](https://user-images.githubusercontent.com/48659981/54499312-821dd700-48cd-11e9-9db5-c169f4efd9d0.png)

Please help if you can. Thank you.

**Comment by w-bruns** [comment]
Does the file really exist?

Winfried

**Comment by w-bruns** [comment]
As I just noticed, there are quotation marks surrounding the file name. They could be a problem. As the error message shows, they are passed to Normaliz, and this must not happen.

**Comment by geraldmorgan13** [comment]
Ya it does .. its in the example file that was included in the zip.with
normaliz

**Comment by w-bruns** [comment]
I think this issue is solved.

**Comment by geraldmorgan13** [comment]
Yes. I had a space when calling the file
