### ISSUE TITLE
configure should error when e-antic is not available and --enable-enfnormaliz is specified

### ISSUE THREAD

**Issue by videlec** [Normaliz/Normaliz#233]
Currently, if dependencies are not met (ie flint and e-antic) the following configure invocation

    ./configure --enable-flint --enable-enfnormaliz

does not error. The outcome is that Normaliz will be built without enfnormaliz support.

**Comment by w-bruns** [comment]
Absolutely right. We should also check conflicts between the existence of other optional packages and the parameters of configure.
