### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by videlec** [Normaliz/Normaliz#234]
Hand made install scripts in the source tarball is a huge pain for package managers (eg conda, Debian, SageMath, ...). It would be much better if the list of dependencies (with versions) would be listed explicitely in the manual or/and in the README. This concerns both optional and mandatory dependencies.

**Comment by w-bruns** [comment]
I don't mind better solutions. If you have one, please offer it.  The dependencies are listed in INSTALL with version numbers. It could be that nauty isn't there yet.

**Comment by w-bruns** [comment]
nauty now added to INSTALL, and INSTALL pished to master on GitHub

**Comment by w-bruns** [comment]
All preprocessor variables controlling the optional libraries are now (un)defined in nmz_config.h.

**Comment by w-bruns** [comment]
Done.
