### ISSUE TITLE
Nauty status

### ISSUE THREAD

**Issue by videlec** [Normaliz/Normaliz#235]
Nauty seems to be an optional dependency of Normaliz. Though it is not listed anywhere in the manual (BTW, it would be good to have a section "dependencies" in the manual, see #234 ). Currently, it seems that building Normaliz without nauty results in segfaults when calling for automorphism group computations. See https://github.com/Normaliz/PyNormaliz/issues/61

**Comment by w-bruns** [comment]
Is official in 3.8.0
