### ISSUE TITLE
Examples and/or tests for Stanley decomposition

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#255]
I noticed that NormalizInterface does not yet support reading out a Stanley decomposition. Adding the missing code is trivial, but of course I want to verify it is correct, and add at least one test case using it. But I couldn't find any existing examples or tests in Normaliz for this. I think it would be beneficial to have a test for this feature in Normaliz itself, too, for the usual reasons (testing for regressions in that code, and of course also helping users understand the feature better).

**Comment by w-bruns** [comment]
Now in test and example.

**Comment by w-bruns** [comment]
Added to 3.8.0
