### ISSUE TITLE
Confusing ./configure --help

### ISSUE THREAD

**Issue by saraedum** [Normaliz/Normaliz#257]
The configure help is somewhat misleading:
```
  --enable-flint[=ARG]    enable flint [default=check]

Optional Packages:
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-flint=DIR        provide location of flint installation prefix or
                          source directory
```

So setting `--without-flint` does not disable the FLINT *dependency* but sets the directory where FLINT can be found to `no`.

It would be nice if this would be closer to common practice, i.e., `--with-flint` forces to build with FLINT dependency, `--with-flint=prefix` builds with FLINT from `prefix` and `--without-flint` disables FLINT (probably the default here.) `--enable/--disable` would go away here because this is feature is fully controlled by a dependency.

This would be of course be a change that breaks some build scripts so it's probably too late for such a change.

**Comment by saraedum** [comment]
cc @isuruf @videlec

**Comment by w-bruns** [comment]
configure.ac must be revised, no doubt.

**Comment by w-bruns** [comment]
Also #233
