### ISSUE TITLE
Generally use c++11 features

### ISSUE THREAD

**Issue by csoeger** [Normaliz/Normaliz#26]
Should we start using the "new" c++11 features?

Thinks that might be usefuI:
* auto
* for_each, ...
* constexpr
* static_assert
* initializer lists

**Comment by w-bruns** [comment]
I think it is a good idea.

Winfried

Am 23.04.2015 um 16:02 schrieb Christof Soeger:
>
> Should we start using the "new" c++11 features?
>
> Thinks that might be usefuI:
>
>   * auto
>   * for_each, ...
>   * constexpr
>   * static_assert
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/26>.
>


-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile) NEW
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by csoeger** [comment]
Most of the mentioned features are included in the most common compiler for several years now, so I think it is no problem to use them. Only the constexpr support does not seem to be widespread, we should not use it for now.

**Comment by csoeger** [comment]
List of supported features for different compilers and when it was introduced:
gcc https://gcc.gnu.org/projects/cxx0x.html
clang http://clang.llvm.org/cxx_status.html
intel https://software.intel.com/en-us/articles/c0x-features-supported-by-intel-c-compiler
clang

**Comment by csoeger** [comment]
We now use the following features witch work with the following compiler versions (according to their web pages)
* long long (gcc 4.3, clang 2.9, icc 11.1)
* static_assert (gcc 4.3, clang 2.9, icc 11.1)
* auto (gcc 4.4, clang 2.9, icc 12.0)
* std::execption_ptr (gcc 4.4, clang 2.9, icc 12.0)

We really want to use the std::exception_ptr, so our minimal requirements are:
gcc 4.4
clang 2.9
icc 12.0
We should try to keep it to this requirements for now.
