### ISSUE TITLE
Strange duplication of content in the manual

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#273]
There is a strange duplication of content in the manual which I don't quite understand, so I can't provide a PR to resolve it... But there is e.g. this:
```
\subsection{Prerequisites}

We require a compiler supporting C++14:
\begin{itemize}
	\item GNU g++ 5,
	\item clang++ 3.4,
	\item Intel icpc 16.0
\end{itemize}
The mentioned compilers are also able to handle OpenMP 3.0, with the exception of clang++, there the first OpenMP support was introduced in 3.7.
```
and then 2300 lines later, this:
```
\subsection{Prerequisites}

We require some C++11 features (e.g. \verb|std::exception_ptr|), supported by:
\begin{itemize}
	\item GNU g++ 4.4,
	\item clang++ 2.9,
	\item Intel icpc 12.0
\end{itemize}
See \url{https://github.com/Normaliz/Normaliz/issues/26} for a more detailed discussion.

The mentioned compilers are also able to handle OpenMP 3.0, with the exception of clang++, there the first OpenMP support was introduced in 3.7.
```

Note that the two section are not completely identical, but clearly they have a common ancestor. The almost-duplication goes on for quite a bit.

**Comment by fingolfin** [comment]
Actually, just as I posted this, I though I should look for `\end{document}`... and it is in line 8754, while the document continues till line 9050. So perhaps those superfluous 300 lines can simply be deleted?

**Comment by w-bruns** [comment]
They have been deleted.
