### ISSUE TITLE
Feature request: Track code coverage using Codecov and/or Coveralls

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#276]
It would be nice if the Travis tests also collected code coverage information and uploaded it to <https://codecov.io> or <https://coveralls.io> or both. This is helpful in identifying code which is never run by the test suite, and for which therefore additional tests should be added (or sometimes, that code just needs to be deleted).

**Comment by w-bruns** [comment]
We should do it -- I assume it is possible.

There is certainly code in Normaliz that can be deleted.

**Comment by w-bruns** [comment]
Now included in Travis builds
