### ISSUE TITLE
nauty is compiled with optimizations

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#278]
In `install_scripts_opt/install_nmz_nauty.sh`, line 49, there is this command: `make all -j4 CFLAGS=-fPIC`. But this means that nauty is compiled with optimizations - its default CFLAGS are something like `-O3 -march=native`, but those flags get dropped.

So, if one uses that script, one gets an unoptimized nauty, which isn't good for performance, obviously.

**Comment by w-bruns** [comment]
O.K. Will be inserted in 3.8.1.
Unfortunately, the way nauty sets up its CFLAGS is not optimal.

**Comment by w-bruns** [comment]
Optimization is not lost. The nauty Makefile has SAFECFLAGS set to -O4.

**Comment by fingolfin** [comment]
I see SAFECFLAGS but it is not working, at least not for me:
```
~/Projekte/foreign/Normaliz/nauty27rc2 (git:mh/travis)$ make all -j4 CFLAGS=-fPIC
gcc -c -fPIC -o naututil.o naututil.c
gcc -c -fPIC -o nautinv.o nautinv.c
gcc -c -fPIC -o traces.o traces.c
gcc -c -fPIC -o gtools.o gtools.c
gcc -c -fPIC -o nauty.o nauty.c
gcc -c -fPIC -o nautil.o nautil.c
...
```

**Comment by fingolfin** [comment]
The `SAFECFLAGS` are only used for *linking* (which is mildly funny, because they have no effect there; but then, neither does -O4 do anything beyond what -O3 does, at least with GCC and clang ;-).

**Comment by fingolfin** [comment]
One way to fix this would be to change `install_nmz_nauty.sh`, replacing `make all -j4 CFLAGS=-fPIC` by `make all -j4 CFLAGS="-O3 -fPIC`. Another would be to patch nauty's `makefile.in`, adjusting the definition of `CCOBJ` from `CCOBJ=${CC} -c ${CFLAGS} -o $@` to `CCOBJ=${CC} -c ${CFLAGS} ${SAFECFLAGS} -o $@`

**Comment by w-bruns** [comment]
Improved in 3.8.1, specifically https://github.com/Normaliz/Normaliz/commit/73d9fb3016d22c5c332561ecb8f54af34eaa45bc
