### ISSUE TITLE
Behavior of Cone getter functions

### ISSUE THREAD

**Issue by csoeger** [Normaliz/Normaliz#28]
How exactly should the Cone getter work?

Possibilities:
1. Return whatever is in the related field of the Cone and do not check if it is even computed. (current approach)
2. Check if it was computed and throw an exception if it wasn't.
3. Check if it was computed and if not, try to compute it. Throw if it does not work out.
4. Check if it was computed and if not, try to compute it, if it wasn't tired before. Throw if it does not work out.

In the current approach 1. the user should check if it was computed. This is not the safest and most user-friendly way. Therefore in the interfaces to CoCoA and GAP we wrap them in the way of option 3.
Should we also do this in the Normaliz interface?

At least we can move from 1. to 2.. The extra isComputed check is not expensive.

We didn't offer 3. so far because:
* It might lead to inefficient usage of libnormaliz, image Cone.getVolume(); Cone.getHilbertSeries();
* It might try to compute something but cannot e.g. because the cone is not pointed. (4. tries to improve this.)
* It can be easily emulated by compute(X), getX().

We can also offer both 2. and 3. with two different methods, or in one method with an optional argument.
If we offer both, then 2. should be the default.

**Comment by csoeger** [comment]
We decided to go for option 3.
How should the exception be called? I started to use `NotComputableException`. Other suggestions?

**Comment by w-bruns** [comment]
I think the name is o.k. I have no better suggestion.

Winfried

Am 03.06.2015 um 11:41 schrieb Christof Soeger:
>
> We decided to go for option 3.
> How should the exception be called? I started to use 
> |NotComputableException|. Other suggestions?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/28#issuecomment-108271383>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile) NEW
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by csoeger** [comment]
All done.
Normaliz itself catches the NotComputableException thrown by .compute(..) and ignores it to write the data we have so far.
