### ISSUE TITLE
Affine dimension can be -1

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#301]
In 3.8.3 (and perhaps earlier) the affine dimension is returned to PyNormaliz via

`size_t Cone<Integer>::getMachineIntegerConeProperty(ConeProperty::Enum property)`

This is not correct since it is -1if the polyhedron is empty. Easiest solution: take long as the return type. This may trigger a change in PyNormaliz.

**Comment by fingolfin** [comment]
Both PyNormaliz and NormalizInterface use `getMachineIntegerConeProperty`; but both user sufficiently generic conversion routines to automatically deal with a switch from `size_t` to `long`, so I don't think there is an issue. I think Normaliz.jl is also fine.

**Comment by w-bruns** [comment]
Return type changed in current master
