### ISSUE TITLE
Stop including .cpp files

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#302]
Currently, several sources files include other sources files, namely the files
- `source/libnormaliz/linear_algebra.cpp`
- `source/libnormaliz/other_algorithms.cpp`
- `source/libnormaliz/cone_and_control.cpp`
- `source/libnormaliz/primal.cpp`
- `source/libnormaliz/enumeration.cpp`

together include the files

- `source/libnormaliz/HilbertSeries.cpp`
- `source/libnormaliz/automorph.cpp`
- `source/libnormaliz/bottom.cpp`
- `source/libnormaliz/cone.cpp`
- `source/libnormaliz/cone_dual_mode.cpp`
- `source/libnormaliz/cone_property.cpp`
- `source/libnormaliz/descent.cpp`
- `source/libnormaliz/full_cone.cpp`
- `source/libnormaliz/general.cpp`
- `source/libnormaliz/input_type.cpp`
- `source/libnormaliz/integer.cpp`
- `source/libnormaliz/list_operations.cpp`
- `source/libnormaliz/matrix.cpp`
- `source/libnormaliz/nmz_integral.cpp`
- `source/libnormaliz/nmz_polynomial.cpp`
- `source/libnormaliz/project_and_lift.cpp`
- `source/libnormaliz/reduction.cpp`
- `source/libnormaliz/simplex.cpp`
- `source/libnormaliz/sublattice_representation.cpp`
- `source/libnormaliz/vector_operations.cpp`

This has several drawbacks:
- it is difficult to see from the outside which .cpp files are compiled directly and which are included by others
- it discourages clean separation of interfaces and implementations
- it leads to longer compilation turnaround times: if I modify a single character in e.g. `general.cpp` (a file with 92 lines), this actually causes `cone_and_control.cpp` to be recompiled, which all in all requires looking at > 8000 lines of code. 

So I'd suggest to try and get rid of this. It won't be trivial, because of course there are reasons for these inclusions (I suspect the use of `template` is a big one). But I think it'd be worth it for developer's convenience alone. Also, afterwards I'd suggest to look into splitting up some of the larger .cpp files, such as `cone.cpp` and `full_cone.cpp`

**Comment by w-bruns** [comment]
The inclusion of cpp files has been eliminated in the current master.
