### ISSUE TITLE
Error running install_normaliz_with_eantic.sh

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#307]
For me, running `install_normaliz_with_eantic.sh` dies in an error like this (I assume other `install_normaliz*.sh` variants are affected as well, but I didn't try):

```
...
OPT_LIB_DIR

installing with --disable-shared
Found see next line
true
Hiding Linux
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
configure: error: source directory already configured; run "make distclean" there first
```

This leaves things in a broken state, as shared libraries were moved to `local/lib/save_dynamic/` and remain there.

**Comment by w-bruns** [comment]
Indeed if the installation breaks down during the installation of the semi-static version, then the so files are not moved back. There is a paragraph in INSTALL mentioning this problem.

But as said already, the semi-static version will be eliminated, and so this problem will also disappear.
