### ISSUE TITLE
failed to build (checking stage) on Alpha architectures

### ISSUE THREAD

**Issue by jgmbenoit** [Normaliz/Normaliz#319]
for details see the [last Debian auto-building log](https://buildd.debian.org/status/package.php?p=normaliz).

**Comment by w-bruns** [comment]
Can Weise the full log?

Frommte tail it has not become clear to me which test fails.

**Comment by jgmbenoit** [comment]
Did you follow the  [alpha link](https://buildd.debian.org/status/fetch.php?pkg=normaliz&arch=alpha&ver=3.8.3%2Bds-1&stamp=1577533001&raw=0) ?

**Comment by w-bruns** [comment]
I have now looked at the full log. My impression: as two years ago, it is a problem with OpenMP. From the full log it becomes clear that Normaliiz is built with -fopenmp. Please try with --enable-openmp=no.

**Comment by jgmbenoit** [comment]
Without OpenMP enabled, it builds fine.
