### ISSUE TITLE
Transfer mkoeppe/Normaliz-bindist to Normaliz/Normaliz-bindist

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#325]
It seems sensible to me that a project resource like this should be part of the Normaliz GitHub organization, not some GitHub user account.

To do this, I think we need to do this (perhaps @mkoeppe can expand on it)

- create a new repo with the right name under the `Normaliz` GitHub organization (@w-bruns needs to do that, i think)
- push the content of the current `Normaliz-bindist` repository there (anybody @w-bruns gives permissions to do that can, e.g. @mkoeppe or myself)
- as outlined in comments in `.make-bindist.sh`, a SSH keypair needs to be created and the keys put into the GitHub config resp. the repository
- finally change `.make-bindist.sh` to reference the new repository location

**Comment by w-bruns** [comment]
I think Max' suggestions are good and realizable. Let us go for them.

**Comment by w-bruns** [comment]
I have created MacBinDist as a repository within Normaliz.

**Comment by w-bruns** [comment]
I have added Max and Matthias as collaborators with "write" status.

**Comment by w-bruns** [comment]
Both promoted to Admin.

**Comment by fingolfin** [comment]
Note that on the long term, I don't think this should be in a repository at all, or at least not in one that keeps on growing (https://github.com/mkoeppe/Normaliz-bindist already is several gigabyte!). 

One could discard the old history from time to time; or just always only keep the last build (though it would be more useful for debugging to keep a few builds).

But even better would be IMHO not to use a git repository at all, but rather e.g. the git release system.

**Comment by w-bruns** [comment]
Sure. In any case we can delete the history of https://github.com/mkoeppe/Normaliz-bindist .
Is there a way to keep only the most recent build log?

Release system? Not completely clear, at least not with every commit pushed to GitHub.

**Comment by fingolfin** [comment]
The "release system" is just a system in which file artifacts can be tracked in GitHub. Think of it as a file server built into GitHub. One can upload binaries there via e.g. Travis jobs. It's not hard. The main issue is how to implement a rotating system where it keeps e.g. "all builds from the last 14 days" or "the last 50 builds" or whatever. Though with a git repository, this is even harder.

Yet another option of course would be to use a classic file server hosted at some university, or in the cloud.

Anyway, babysteps: for now I am happy to report that the Travis jobs for https://github.com/mkoeppe/Normaliz-bindist are working again.

**Comment by w-bruns** [comment]
Thanks for the repair!

I suggest that we wait with any changes until after the next release. It should happen in the next three weeks.

**Comment by w-bruns** [comment]
Now 3.8.4 has been released. The experts can make the changes.

**Comment by fingolfin** [comment]
I forgot about this, will take a fresh look

**Comment by w-bruns** [comment]
The purpose of the biondist repository is now reached by storing an "artifact"  GitHub actions produced by GitHub actions.

Normaliz bindist has not been used yet and will be deleted.
