### ISSUE TITLE
Status of Docker images?

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#326]
Some questions and observations:
- Who is in control of the user account https://hub.docker.com/u/normaliz ? Is it @sebasguts ? Also @w-bruns ?
- Who is in control of the repository https://hub.docker.com/r/normaliz/normaliz (presumably just that user above and the people in control of it)
- Who is taking care of updating https://hub.docker.com/r/normaliz/normaliz ? Nobody? (Given that https://hub.docker.com/r/normaliz/normaliz/tags has 3.7.2 as latest tagged release, and `latest` is  3 months old, too)
- Can we update these things automatically? I.e. instruct DockerHub to automatically fetch our releases, and/or add a Travis CI script or a GitHub Action to automatically update DockerHub?

**Comment by w-bruns** [comment]
The Docker releases are produced automatically from GitHub commits, namely "master" from the GitHub branch wit the same name and "latest" from the GitHub branch release.  The age of "latest is therefore 0.k. It has been produced from Normaliz 3.8.3. Perhaps the tags on GitHub have not been taken care of as they should.

In short: the Docker builds are up-to-date.

The ownership questions will be investigated.

**Comment by w-bruns** [comment]
The owners are sebaguts and wbruns.

**Comment by w-bruns** [comment]
Correction: the Docker repository is not up-to-date in regard to master. 

 The builds were tried but failed because libflint was not found.

**Comment by w-bruns** [comment]
Concerning tags: are these really necessary on Docker? I don't think they are as long as the automatic builds work.

**Comment by w-bruns** [comment]
Final comments:
1) The owner of the repository is the organization normaliz.
2) The owners of the organization are sebaguts, wbruns and (now) fingolfin.
3) The Docker builds work again after a problem in install_normaliz.sh has been solved.
4) "latest" and "master" are tags.
