### ISSUE TITLE
Status of website

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#327]
The current website at https://www.normaliz.uni-osnabrueck.de is using WordPress. That means that we can not really update it via scripts (at least not w/o some nasty hacking). It is also unclear to me who has write access to it (just @w-bruns ?)

And who is updating it? Some pages, e.g. <https://www.normaliz.uni-osnabrueck.de/home/the-normaliz-team/>, seem somewhat outdated.

It also has things like PDF files with references, which IMHO really would be much better as HTML files (there are tools to convert .bib files to nice .html).

How about replacing it with a static website using GitHub Pages and Jekyll? Then the website data could be in a separate `gh-pages` branch of this git repository, or alternatively in its own git repository. Downloads could all be handled via the GitHub release system.

Then updating the website for a new release could be fully scripted. Also, editing it would be done by editing and pushing a git repository, which I personally prefer over Wordpress (but that's just me, I understand that most people feel the reverse ;-).

The only thing not quite clear to me is whether we could keep using the URL https://www.normaliz.uni-osnabrueck.de with that system -- in principle this is can be done, the only question is whether the University Osnabrück allows setting a CNAME DNS record for this domain? The alternative would be to use `normaliz.github.io` and let the old domain redirect to the new. Or somebody agrees to pay for a custom domain name (`normaliz.org` and multiple others seem to be still available).

I could help with setting up a new website using Jekyll, but I am not sure this is desired; there might also be more dynamic features of the old website I am simply not aware of.

**Comment by w-bruns** [comment]
The web site is maintained by Tim Römer. We will update it with the next release., at least within February.  Then we can come back to all the questions and suggestions above.

**Comment by w-bruns** [comment]
The website is now up-to-date. For the time being, we should not touch it.
