### ISSUE TITLE
Don't force MPIR on Windows

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#334]
Right now, `general.h` contains this:

```C
...
#ifdef _WIN32     // for 32 and 64 bit windows
#define NMZ_MPIR  // always use MPIR
#endif

#ifdef NMZ_MPIR  // use MPIR
#include <mpirxx.h>
#else  // otherwise use GMP
#include <gmpxx.h>
#endif
...
```

I consider this a bug, but first I'd like to understand why we "force" MPIR on Windows anyway?

I'd like use to stop doing that, and either only use GMP (easiest option for us, and should be sufficient given that MPIR has a GMP compatibility layer), or else we ought to properly detect MPIR vs. GMP in `configure` (offering a `--with-mpir=...` option; and if it is used together with `--with-gmp`, we produce an error). Then, if we still for some reason want to force building Normaliz with MPIR on Windows, we can do so by providing this setting to the build system, instead of hardcoding it.

I was made aware of this by @benlorenz in https://github.com/JuliaPackaging/Yggdrasil/pull/625

**Comment by w-bruns** [comment]
cc @isuruf

It is certainly not a bug, but works very well. 

Before we change anything, we must make sure that there is no problem for the Conda builds.

**Comment by fingolfin** [comment]
No offense intended; I personally would consider this a bug simply because it is unexpected behavior (to me, at least) that if I select `--with-gmp`, I might still run into a compiler error because the code tries to use MPIR instead...

**Comment by isuruf** [comment]
@w-bruns, conda package installs `gmpxx.h` which is a copy of `mpirxx.h` so changing it here is fine.

MPIR is a fork of GMP and is very similar on unix. On windows, for eg: `mpz_add_ui` takes in an `unsigned long (32 bit)` on GMP and `unsigned long long (64 bit)` on MPIR. On unix, both use `unsigned long (64 bit)`.

**Comment by fingolfin** [comment]
That said, I understand that the change was made to fix (?) some actual other issue, or get something working. But I would hope that e.g. Conda could get the same result by explicitly adding `-DNMZ_MPIR` to the `CPPFLAGS`, or using a (to be added) configure option `--with-mpir`.

In the meantime, @benlorenz reported that removing the `NMZ_MPIR` check and thus using GMP results in errors like these:
```
./libnormaliz/HilbertSeries.cpp:1122:26: error: ambiguous overload for ‘operator*’ (operand types are ‘size_t {aka long long unsigned int}’ and ‘__gnu_cxx::__alloc_traits<std::allocator<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> > >::value_type {aka __gmp_expr<__mpz_struct [1], __mpz_struct [1]>}’)
./libnormaliz/cone.cpp:5322:18: error: ambiguous overload for ‘operator*=’ (operand types are ‘mpz_class {aka __gmp_expr<__mpz_struct [1], __mpz_struct [1]>}’ and ‘size_t {aka long long unsigned int}’)
./libnormaliz/cone.cpp:5865:26: error: ambiguous overload for ‘operator=’ (operand types are ‘mpq_class {aka __gmp_expr<__mpq_struct [1], __mpq_struct [1]>}’ and ‘size_t {aka long long unsigned int}’)
./libnormaliz/cone.cpp:5865:26: error: ambiguous overload for ‘operator=’ (operand types are ‘mpq_class {aka __gmp_expr<__mpq_struct [1], __mpq_struct [1]>}’ and ‘size_t {aka long long unsigned int}’)
./libnormaliz/cone.cpp:6771:18: error: ambiguous overload for ‘operator=’ (operand types are ‘mpq_class {aka __gmp_expr<__mpq_struct [1], __mpq_struct [1]>}’ and ‘size_t {aka long long unsigned int}’)
./libnormaliz/full_cone.cpp:3050:38: error: conversion from ‘size_t {aka long long unsigned int}’ to ‘const value_type {aka const __gmp_expr<__mpz_struct [1], __mpz_struct [1]>}’ is ambiguous
./libnormaliz/full_cone.cpp:6036:5: error: conversion from ‘size_t {aka long long unsigned int}’ to ‘std::vector<__gmp_expr<__mpz_struct [1], __mpz_struct [1]> >::value_type {aka __gmp_expr<__mpz_struct [1], __mpz_struct [1]>}’ is ambiguous
```

I've seen that before; I might know a way or to to resolve this and thus allow for using GMP after all. But it'll take me a moment to setup a Windows VM etc. to test it.

**Comment by fingolfin** [comment]
Ah I overlapped with @isuruf -- yeah, `long` vs `long long` difference between Windows and Linux are part of the issue. We run into this in `NormalizInterface`, too, but were able to resolve this by carefully tweaking our template definitions. Whether this is possible with reasonable effort for Normaliz is another question... :-)

**Comment by w-bruns** [comment]
cc @isuruf

I have pushed the branch no_mpir to GitHub.  Please try to build it for Conda. If this should be successful, we can omit MPIR in the future.

**Comment by w-bruns** [comment]
Is now realized. MPIR only used for "private" compilations by the Normaliz team.
