### ISSUE TITLE
Shift

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#34]
The shift should be determined as follows:

The reference object is the monoid (or module) M defined by the input. We print the Hilbert series of M(s) where s is the shift.

Example: the lowest degree in the module is -1. In order to have the Hilbert series starting in degree 0 we must pass to M(-1). So the shift is -1.

This convention has the pleasant effect that the shift names the lowest degree in M.

**Comment by csoeger** [comment]
I agree. We really have to emphasize these changes in the Manual.

**Comment by w-bruns** [comment]
Will be empgasized.

Winfried

Am 18.06.2015 um 16:05 schrieb Christof Soeger:
>
> I agree. We really have to emphasize these changes in the Manual.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/34#issuecomment-113167322>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by csoeger** [comment]
For the library interface the shift should be a part of the HilbertSeries, not in Cone directly. Therefore also the ConeProperty::Shift can be removed.

**Comment by csoeger** [comment]
Done
