### ISSUE TITLE
Build failure on ubuntu-trusty

### ISSUE THREAD

**Issue by mkoeppe** [Normaliz/Normaliz#346]
As reported in https://trac.sagemath.org/ticket/27952#comment:70
and as can be seen in GH Actions.

**Comment by w-bruns** [comment]
I presume this is not a Normaliz internal issue.

**Comment by fingolfin** [comment]
It's rather difficult to follow that conversation, and to decide which of the many issues which are mashed together there are still current and which not, and how to reproduce them etc.

As to the `isnan` issue, googling for that leads to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60407  (however, the error on the SageMath trac seems to be cut off? So I am not 100% sure its the same). Anyway, the suggestion there is that it might be a problem to use math.h and instead one should `#include <cmath>` instead (which is indeed the recommendation for C++ code; similar for other headers, e.g. `stdlib.h` -> `cstdlib` etc.)

I did this in PR #347.

If that doesn't help, two more things one can try to help with the `isnan` issue:
1. avoid `using namespace std` (which is in general discouraged); but that may require *way* too much effort (that said, let me point out that it *definitely* should be avoided in headers
2. explicitly write `std::isnan`.

**Comment by mkoeppe** [comment]
> It's rather difficult to follow that conversation, and to decide which of the many issues which are mashed together there are still current and which not, and how to reproduce them etc.

I agree, it's a complicated ticket. Let's address the issues on separate tickets here on the Normaliz issue tracker.

> As to the `isnan` issue, googling for that leads to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60407 (however, the error on the SageMath trac seems to be cut off? So I am not 100% sure its the same). Anyway, the suggestion there is that it might be a problem to use math.h and instead one should `#include <cmath>` instead (which is indeed the recommendation for C++ code; similar for other headers, e.g. `stdlib.h` -> `cstdlib` etc.)
> 
> I did this in PR #347.

Great. Let's wait for the CI to test it. 

Of course, ubuntu-trusty is an ancient system with an ancient compiler (gcc 4.x). In the long run there will be the question where Normaliz (and Sage) wants to continue to support it. But right now, it's the single line with the isnan that is breaking compatibility and so it would be nice to fix it.

**Comment by fingolfin** [comment]
Other than that, there seem to be lots of failures that are not under the control of Normaliz. E.g.:
- `cygwin (minimal)` fails building Flint 2.5.2
- `cygwin (standard)` fails building e_antic-0.1.7
- `docker (debian-buster, standard)` also fails building e_antic-0.1.7
- `docker (ubuntu-trusty, minimal)` fails in a GitHub action setting with the rather unhelpful title `Run set -o pipefail; EXTRA_DOCKER_BUILD_ARGS="--build-arg USE_MAKEFLAGS=\"-k V=0 SAGE_NUM_THREADS=3\"" tox -e $TOX_ENV -- $TARGETS 2>&1 | sed "/^configure: notice:/s|^|::warning file=artifacts/$LOGS_ARTIFACT_NAME/config.log::|;/^configure: warning:/s|^|::warning file=artifacts/$LOGS_ARTIFACT_NAME/config.log::|;/^configure: error:/s|^|::error file=artifacts/$LOGS_ARTIFACT_NAME/config.log::|;"` ... Looking into this, I just found "core dump" error while starting up Docker (?) After digging around more, I finally also found what looks like parts of a compiler error this one is affected by that `isnan` issue mentioned on the SageMath Trac. But fishing this out of the log is really cumbersome
- `docker (centos-7, minimal)` also seems to be related to `isnan`, so let's see whether PR #347 helps with it (in
- `docker (linuxmint-17, standard)` failed building Normaliz... somehow? The error log is too short to tell, at  least I couldn't find the actual error? The log for normaliz seems to start like this:
```
  [normaliz-git]   make[3]: *** [dynamic/dynamic.o] Error 1
  [normaliz-git]   make[3]: *** [maxsimplex/maxsimplex.o] Error 1
  [normaliz-git]   make[3]: *** [libnormaliz/collection.lo] Error 1
  ...
```
so it cuts off right after the actual error?

I gave up at that point, as I found it far too frustrating to dig through these logs :-(

**Comment by fingolfin** [comment]
OK, one more: ` docker (debian-bullseye, stanard)` fails with this:
```
E: Package 'python3.7' has no installation candidate
E: Unable to locate package libpython3.7-dev
E: Couldn't find any package by glob 'libpython3.7-dev'
E: Couldn't find any package by regex 'libpython3.7-dev'
```

**Comment by mkoeppe** [comment]
> I did this in PR #347.

This does not seem to have helped with `ubuntu-trusty`.

**Comment by mkoeppe** [comment]
> * `docker (linuxmint-17, standard)` failed building Normaliz... somehow? The error log is too short to tell, at  least I couldn't find the actual error? The log for normaliz seems to start like this:
> 
> ```
>   [normaliz-git]   make[3]: *** [dynamic/dynamic.o] Error 1
>   [normaliz-git]   make[3]: *** [maxsimplex/maxsimplex.o] Error 1
>   [normaliz-git]   make[3]: *** [libnormaliz/collection.lo] Error 1
>   ...
> ```
> 
> so it cuts off right after the actual error?

There are two ways how you can see more:

1) Open " Print out logs for immediate inspection". This will show all logs of failing packages

2) When all builds have finished, you will be able to download all logs as a big zip file.

**Comment by mkoeppe** [comment]
> OK, one more: ` docker (debian-bullseye, stanard)` fails with this:
> 
> ```
> E: Package 'python3.7' has no installation candidate
> E: Unable to locate package libpython3.7-dev
> E: Couldn't find any package by glob 'libpython3.7-dev'
> E: Couldn't find any package by regex 'libpython3.7-dev'
> ```

I have just merged a fix for this into https://trac.sagemath.org/ticket/27952 .
The next runs should be picking this up automatically.

**Comment by mkoeppe** [comment]
> in a GitHub action setting with the rather unhelpful title `Run set -o pipefail; EXTRA_DOCKER_BUILD_ARGS="--build-arg `...

#351 makes this title prettier
