### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#35]
It would be nice to have shortcuts for certain vectors and matrices.

So far mentioned in the manual: 
   nonnegative: stands for signs with all entries 1
   total_degree; stands for grading with all entries 1

Desirable:
   unit_vector i: the i-th unit vector
   last_coordinate: the d-th unit vector for amb_space d
   unit_matrix: the d xd unit matrix

For the vectors we must decide whether they can occur everywhere, for example as a row of a matrix or only at places where a vector is asked for, namely grading or dehomogenization.

**Comment by csoeger** [comment]
If we allow e.g. unit_vector as row in a matrix we have to allow to give a combination of such rows and rows given by the entries. We should have a look at possible examples and see if we really likes it.

For totaldegree we always use one of the lengthmof amb_space? Does it also fit for special modes like rees_algebra, lattice_ideal, ...

**Comment by w-bruns** [comment]
The vectors grading and dehomogenization have ALWAYS the length d given 
by amb_space. The numbers of columns of the various matrices are derived 
from it (d-1,d,dü1,d+2).

Winfried

Am 18.06.2015 um 16:24 schrieb Christof Soeger:
>
> If we allow e.g. unit_vector as row in a matrix we have to allow to 
> give a combination of such rows and rows given by the entries. We 
> should have a look at possible examples and see if we really likes it.
>
> For totaldegree we always use one of the lengthmof amb_space? Does it 
> also fit for special modes like rees_algebra, lattice_ideal, ...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/35#issuecomment-113172032>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by w-bruns** [comment]
total_degree and nonnegative done.

Rest postponed.

**Comment by csoeger** [comment]
Also allow unit_vector for all vector inputs, but not as row of a matrix, also not if the matrix has only one row in this case.
