### ISSUE TITLE
add xz tarball

### ISSUE THREAD

**Issue by vtorri** [Normaliz/Normaliz#360]
hello

would it be possible to add xz archive ? with autotools, it's a matter of adding dist-xz here : 

https://github.com/Normaliz/Normaliz/blob/master/configure.ac#L34

thank you

**Comment by fingolfin** [comment]
The .tar.gz is 4.35 MB. What's the motivation for wanting a .tar.xz I wonder?

It may or may not be "easy" to add it, but every extra step in the release process introduce another potential point of failure (e.g. if xz is not installed on the machine). Not adding it certainly is even easier for us...
