### ISSUE TITLE
MacOS Intel binary provided in releases runs on Apple M1

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#361]
Nevertheless we hope to provide a version compiled for the M1 processor in the near future.

**Comment by mahrud** [comment]
The brew formula I mentioned in https://github.com/Normaliz/Normaliz/issues/246#issuecomment-994665211 also builds Normaliz successfully on M1.

**Comment by w-bruns** [comment]
Have you run the test suite with your binary? Unfortunately it has turned out that the Mac binaries in our releases >= 3.8.10 can crash or, worse, produce wrong results if run with more than 1 thread. See https://github.com/Normaliz/Normaliz/issues/383.

As far as I can tell now, it seems to be a problem related to the clang computation. All gcc builds don't show this problem, and under Linux we have only observed it for clang 11; see https://github.com/Normaliz/Normaliz/issues/374.
