### ISSUE TITLE
Limit the Sage CI tests

### ISSUE THREAD

**Issue by fingolfin** [Normaliz/Normaliz#366]
The Sage CI test set up by @mkoeppe via `.github/workflows/ci-sage.yml` currently start around 80 CI jobs. Even though we are allowed to run 40 jobs in parallel (because we requested and received recognition as an academic project), this means that it takes a loooong time to just process the CI tests for a single pull request. It's actually a bit worse, because there are also a bunch of macOS jobs in there, which have additional limits.

This didn't matter so much in the past, when we still used Travis CI as our primary CI provider, and the Sage tests just run in addition, and could be ignored. But now they use the same resources as our primary CI tests, and that means that if one waits for the results of, say, three PRs (as is the case right now), it can be hours before one gets any feedback on the CI status of those PRs.

Here are some potential ways how we could address this (not mutually exclusive).

1. Perhaps GitHub Action allows to limit the number of runners that are tasked with handling a given Workflow file; I don't know if that's the case, but *if* there is such a feature, we could use it to limit the number of concurrent jobs to be used when processing `.github/workflows/ci-sage.yml`, so that our own CI tests can be processed first
2. The number of test jobs in `.github/workflows/ci-sage.yml` could be reduced, possibly drastically. Eg. do we really need to test on 12 Fedora variants (version 26-31, minimal and standard variants for each)?
3. Instead of running these tests on every PR, we could limit them to `master` (or not even run them there by default), and instead have them use a manual trigger; i.e., there will be a button that allows running them on a specific PR or branch. For an example where this is done, see this workflow file: https://github.com/oscar-system/GAP.jl/blob/master/.github/workflows/PackageCI.yml

While I am typing this, I also notice that many (all?) of those Sage CI tests currently fail with the error "cp: cannot stat '.tox/docker-ubuntu-trusty-standard/Dockerfile': No such file or directory".  Perhaps someone (@mkoeppe ?) can provide a fix; if not, I suggest we simply disable this workflow until it ca be fixed (by going to https://github.com/Normaliz/Normaliz/actions?query=workflow%3A%22Run+Sage+CI+for+Linux%2FCygwin%2FmacOS%22 then clicking on the button with the three dots (... great UI, GitHub 😞  ) and selecting "Disable workflow") -- it can be re-enabled at any time later.

**Comment by fingolfin** [comment]
OK, I should have waited a bit longer -- the original point of this PR seems to be somewhat moot, because it turns out that GitHub Actions already seems to be making sure that not all runners are occupied by a single workflow? At least I see it still waiting for dozens of Sage CI jobs for my first PR, while already processing some of the basic CI jobs for my "third" PR (which is actually an old one that I just rebased). 

However, the issue of the Sage CI jobs being broken remains (and I also still wonder if we *really* need to run all those 80 jobs -- even if it does not impede us much, this is a lot of energy that is wasted every time..)

**Comment by mkoeppe** [comment]
The workflow already limits the parallel actions using the `max-parallel` keyword. You can edit it to reduce it further. 

Yes, limiting it to run on master only -- in preparation for tagging a new release -- can certainly also make sense. 

I hope to update the workflow soon using the latest version from Sage.

**Comment by saraedum** [comment]
> because we requested and received recognition as an academic project

Sorry, that's off-topic, but do you remember where this can be requested? @fingolfin

**Comment by fingolfin** [comment]
@saraedum sorry for only replying now, I didn't notice your comment here. First, you need to get edu status for your GitHub account via https://education.github.com/benefits. Afterwards, it is hidden a bit in the set of all "discounts" this enables (see <https://education.github.com/toolbox/offers>): there the very last item is GitHub specific discounts, which links to <https://education.github.com/toolbox/offers/github-org-upgrades>.

**Comment by w-bruns** [comment]
Can we close this issue?
