### ISSUE TITLE
Compatibility with e-antic 1.0.0

### ISSUE THREAD

**Issue by saraedum** [Normaliz/Normaliz#367]
I just started to make Normaliz work with the upcoming e-antic 1.0.0. Since this introduces a couple of breaking API changes, I wonder which path I should take here… keep the code compatible with e-antic 0.1.8 by introducing (quite) a few `#ifdef` clauses or drop support for 0.1.8 and require 1.0.0 with a cleaner code base.

What's your preference here? cc: @fingolfin @videlec

**Comment by videlec** [comment]
To me it is fine to drop support for the 0.1.X e-antic branches.

**Comment by w-bruns** [comment]
What are the exact requirements for the C++ compiler? The compilers coming with Ubuntu 18-04 should be sufficient.
Otherwise I would go for 1.0.0 version of e-antic. Sooner or later we must do it anyway.

**Comment by saraedum** [comment]
C++14 should be good enough I think. When I do `apt install g++` in Ubuntu 18-04 I get GCC 7 which supports virtually all of C++17 (and all of C++14.) Ok. I'll try to prepare a pull request then.

**Comment by w-bruns** [comment]
Excellent. I am looking forward to it.

**Comment by w-bruns** [comment]
The branch new_e-antic is adapted to e-antic 1.0.0. However, it seems that e-antic 1.0.0, as of today, has performance problems. 

The master branch which has alreday been adapted to e-antic 1.0.0 will be set back to 0.1.8 today.

**Comment by w-bruns** [comment]
Correction: in the next days the branches will be changed as follows:
**main** is the new default branch, based on e-antic 0.1.8
**new_e-antic_in_master** is adapted to e-antic 1.0.0
**master** will disappear, as well as **new_eantic**
**release** has kept its role

**Comment by w-bruns** [comment]
Because we could not change the DockerHub settings of our automated builds, we renamed `main` to `master`. Sorry for the turbulence.

**Comment by w-bruns** [comment]
We plan e-antic 1.0.0 for Normaliz 3.9.0.

**Comment by w-bruns** [comment]
Done.
