### ISSUE TITLE
Fails to find CoCoALib: CoCoALib is not available but was requested

### ISSUE THREAD

**Issue by yurivict** [Normaliz/Normaliz#379]
```
checking whether CoCoALib headers and library are available... no
configure: error: CoCoALib is not available but was requested
===>  Script "configure" failed unexpectedly.
```

cocoalib-0.99712 is installed.

config.log contains these details:
```
configure:18228: checking whether CoCoALib headers and library are available
configure:18251: c++ -o conftest -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -fno-omit-frame-pointer -isystem /usr/local/include    -fstack-protector-strong    conftest.cpp -L/usr/local/lib -lcocoa -lgmpxx -lgmp >&5
In file included from conftest.cpp:28:
In file included from /usr/local/include/CoCoA/library.H:11:
In file included from /usr/local/include/CoCoA/BigIntOps.H:23:
In file included from /usr/local/include/CoCoA/MachineInt.H:26:
/usr/local/include/CoCoA/ULong2Long.H:31:3: error: expected unqualified-id
  "ERROR: -DCoCoA_ULONG2LONG=n setting missing";
  ^
```

Additionally, cocoalib itself depends on ```Normaliz``` so that there is a circular dependency.

OS: FreeBSD 13

**Comment by w-bruns** [comment]
CC John.Abbott@uni-passau.de bigatti@dima.unige.it

As far as I can see, the problem is not that CoCoALib is not found, but results form the installation of CoCoALib.

As to the circular dependence, we have never observed a problem in the installation of CoCoALib without having installed Normaliz previously. You can see this in the CI builds on GitHub and also in our Docker builds.

If you want to use Normaliz from CoCoA (and install Normaliz with CoCoALib), then a second build of CoCoA may be necessary.

**Comment by JohnAbbott-cocoa** [comment]
CoCoALib can use libnormaliz as an optional "external library"; as Bruns says, you should probably first install
CoCoALib without libnormaliz, then use that to compile libnormaliz/Normaliz, and then rebuild a new version of
CoCoALib with libnormaliz (if that is what you want).

I do not know how you managed to obtain the error message about -DCoCoA_ULONG2LONG.
The CPP symbol/macro should be defined in the file include/CoCoA/PREPROCESSOR_DEFNS.H
and this file should be produced automatically by the configure script for CoCoALib.

Could you show what is in the CoCoA files: configuration/autoconf.mk   and   include/CoCoA/PREPROCESSOR_DEFNS.H

**Comment by w-bruns** [comment]
What is the status of this issue?
