### ISSUE TITLE
some tests failed on 32bits architectures

### ISSUE THREAD

**Issue by jgmbenoit** [Normaliz/Normaliz#388]
See the latest Debian auto-building status [here](https://buildd.debian.org/status/package.php?p=normaliz) for version `3.9.2`.
For example, on `i386` arch, we get:
```
< min_poly (a^32 - 5) embedding [1.05158119849597691289566023544418261961696011833 +/- 4.42e-48]
---
> min_poly (a^32 - 5) embedding [1.05158119849597691289566 +/- 2.27e-24]
```

**Comment by w-bruns** [comment]
This is again a floating point problem. I must extend the list of exceptions for non-strict tests in test/Makfefile.classic. Patch wi8ll come.

**Comment by w-bruns** [comment]
Replace line 13 of `test/Makefile.classic` by

`DIFF = diff -b -I ".*embedding.*\|.*resulting.*\|.*triangulation.*\|.*float.*\|.*fixed.*"`

**Comment by jgmbenoit** [comment]
Thanks for your prompt reply. It rocks !
