### ISSUE TITLE
Normaliz uses only 8 cores by default

### ISSUE THREAD

**Issue by maxale** [Normaliz/Normaliz#394]
By default Normaliz restricts itself to using only 8 cores even if more cores are available in the system. 

I'd like to request changing this behavior to using ALL available cores by default. Limiting to 8 cores appears to be a rather arbitrary choice.

**Comment by w-bruns** [comment]
Without a bound Normaliz would greedily create a very high number of threads for small computations on some systems. 

You can disable the bound by the option `-x=0`.
