### ISSUE TITLE
Computing Hilbert Bases

### ISSUE THREAD

**Issue by nclskoh** [Normaliz/Normaliz#399]
Hi,

I ran into some problems computing the Hilbert basis of a problem, and I'm not sure if I'm hitting a bug or using Normaliz wrongly.

Given the input:

> amb_space 4
cone 3
                  0    4294967296                     0 -4294967295
4294967296                      0  -4294967296 -4294967295
                  0   -4294967296   4294967296  4294967295

Running `./normaliz -N` on this file to compute Hilbert bases crashes with the error: 

> source/libnormaliz/matrix.cpp:2922: std::vector<Integer> libnormaliz::Matrix<Integer>::solve_rectangular(const std::vector<Integer>&, Integer&) const [with Integer = long long int]: Assertion `nc == Left_Side.nr' failed

Perturbing the numbers mostly works fine, although just perturbing the second column a little causes an error.

> amb_space 4
cone 3
                  0    4294967295                     0 -4294967295
4294967296                      0  -4294967296 -4294967295
                  0   -4294967295   4294967296  4294967295

> Some error in the normaliz input data detected: Grading gives non-positive value -4294967295 for generator 3.

Does the crash have to do with the input being close to the boundary of int, with 4294967296 = 2^32? Also, what does the error mean?

Thanks! I apologize if this isn't the right place to be asking such a question; please let me know if this should go elsewhere instead.

**Comment by w-bruns** [comment]
I  will try to investigate the problem.

**Comment by w-bruns** [comment]
As a temporary solution I suggest that you run it with the option -B. Then you will see that the computation of the Hilbert basis is presumably hopeless.

Nevertheless, the assert should not happen. I will now have a closer look.

**Comment by w-bruns** [comment]
It seems that the Normaliz overflow check fails for your computation at a certain point. It is not, and cannot be, 100% fail proof. As said, use -B to do all computations in indefinite precision. I will replace the assert by an exception whose text says hat you should rerun your computation with -B.

**Comment by nclskoh** [comment]
Thanks very much, appreciate it.

**Comment by w-bruns** [comment]
I have now changed the code in such a way that the switch to indefinite precision is automatic, provided you haven't used LongLong, which would exclude the switch.

Will be part of the next release.
