### ISSUE TITLE
Index in Normaliz

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#4]
We can distingusih at least three lattices in Normaliz:

A, the ambient lattice
E, the effective lattice
G, the lattice generated by the input vectors

Note that we define G by the input vectors in the coordinates of E AFTER having made them coprime. 

Question: what are original generators, the true input or the coprime versions?

If L is a taiice and U a sublattice, we call the order [L:U] of the torsion subgroup of L/U the index of U in L. It is the index in the traditional sense if rank U = rank L.

The index that Normaliz computes at present is [E:G]. It would be useful to compute [A:E] as well.

Under the compoistion of sublattice representations, [A:E] is multiplicative while the total index [A:G] is constant.

**Comment by w-bruns** [comment]
The external index A:E has been implemenred.

Note A:E is not multiplicative in general, contrary to what is claimed above.

The internal index E:G is problematic since it is difficult to say precisely what G is. Perhaps we will remove it.

**Comment by csoeger** [comment]
The old index is now removed from the output.
