### ISSUE TITLE
Can this tool be used to study the space group related problems?

### ISSUE THREAD

**Issue by hongyi-zhao** [Normaliz/Normaliz#406]
It's well known that a space group can be represented as an affine group. So I want to know whether this tool can be used to study the space group related problems. Any tips will be greatly appreciated.

Regards,
Zhao

**Comment by w-bruns** [comment]
To answer your question I must know what a space group is and what is to be computed for them.

**Comment by hongyi-zhao** [comment]
> To answer your question I must know what a space group is

1.  A space group of dimension n is represented by an (n+1)-dimensional rational matrix group as described [here](https://docs.gap-system.org/pkg/crystcat/htm/CHAP001.htm#SECT002):

![image](https://user-images.githubusercontent.com/11155854/217222830-0cb702d5-fb71-49b4-9bfc-cb924f5a20bc.png)

Here is an example:

```gap
gap> S:=SpaceGroupOnLeftIT(3,227);
SpaceGroupOnLeftIT(3,227,'2')
gap> GeneratorsOfGroup(S);
[ [ [ -1, 0, 0, 3/4 ], [ 0, -1, 0, 1/4 ], [ 0, 0, 1, 1/2 ], [ 0, 0, 0, 1 ] ], [ [ -1, 0, 0, 1/4 ], [ 0, 1, 0, 1/2 ], [ 0, 0, -1, 3/4 ], [ 0, 0, 0, 1 ] ], 
  [ [ 0, 0, 1, 0 ], [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 0, 1 ] ], [ [ 0, 1, 0, 3/4 ], [ 1, 0, 0, 1/4 ], [ 0, 0, -1, 1/2 ], [ 0, 0, 0, 1 ] ], 
  [ [ -1, 0, 0, 0 ], [ 0, -1, 0, 0 ], [ 0, 0, -1, 0 ], [ 0, 0, 0, 1 ] ], [ [ 1, 0, 0, 1/2 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 1/2 ], [ 0, 0, 0, 1 ] ], 
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 1/2 ], [ 0, 0, 1, 1/2 ], [ 0, 0, 0, 1 ] ], [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 1 ], [ 0, 0, 0, 1 ] ] ]
```
And the corresponding generators given by BCS are [here](https://www.cryst.ehu.es/cgi-bin/cryst/programs//nph-getgen?gnum=227&what=gen):

![image](https://user-images.githubusercontent.com/11155854/217223977-e9ecad51-a3d6-4f1b-98dc-10f9832874de.png)

> and what is to be computed for them.

Here are some problems I would like to address about space groups:

2.1 The isomorphism determination between such two groups, as represented [here](https://github.com/spglib/spgrep/issues/24#issue-1345371642).
2.2 The minimal generating set determination of such a group, as represented [here](https://github.com/gap-packages/grape/issues/45#issuecomment-1344817981).

**Comment by w-bruns** [comment]
Normaliz is not a tool for group theory. Perhaps GAP or Magma can help you.

I have not approved your mail via the mailing list since the list is only for announcements.
