### ISSUE TITLE
MacOS binary of 3.10.3

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#425]
`libomp.dylib` is not correctly bound to `normaliz`. If you don't need the new features of 3.10.3, stay with 3.10.2. Otherwise the Docker image is a way out.

**Comment by mahrud** [comment]
The homebrew build (`brew install macaulay2/tap/normaliz`) is definitely linked with `libomp.dylib` and is at version 3.10.3.

**Comment by w-bruns** [comment]
Have you run the tests? Ther `Trace/BPT trap: 5` occurs only for some  tests.

**Comment by mahrud** [comment]
As far as I can tell, `make check` passes successfully on macos-12 and 13 on x86_64 and macos-14 on arm64: https://github.com/Macaulay2/homebrew-tap/actions/runs/9728460850/job/26849226167

**Comment by w-bruns** [comment]
The MacOS binary of 3.10.3 has been replaced by a version produced under MacOS 12.
