### ISSUE TITLE
Triangulation: nested and plain --> <project>.tri

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#49]

**Comment by csoeger** [comment]
Should it be just a single string at the end of the file?

**Comment by w-bruns** [comment]
Yes.

Winfried

**Comment by csoeger** [comment]
Suggestion:
Add functions `bool isTriangulationPartial()` and `bool isTriangulationNested()`. The corresponding internal `bool`s in `Cone` are updated whenever the  `Triangulation` or `TriangulationSize` is updated.
But then we should delete the Triangulation when we compute a new (e.g. partial) Triangulation.

**Comment by csoeger** [comment]
These two types of "triangulations" are now marked. Information is printed by Normaliz in .out and .tri file.
Partial is activated when the first simplex or pyramid is skipped because of height 1.
Nested is activated when the first simplex is successfully subdivided.
