### ISSUE TITLE
Parallelization of computation of quasipolynomial

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#55]

**Comment by w-bruns** [comment]
The suggested parallelization does not have a significant effect. 

The main problem is the multiplication that is necessary for the "universal" denominator. Potential solution: Karatsuba.

**Comment by csoeger** [comment]
John Abbott suggested to change the multiplication and actually use that the polynomials we multiply by are sparse (if represented correctly). This has a very good effect, e.g. an test example of period 5040 the quasipolynomial computation time went down from over 6 min to less than 10 sec. I don't think it is necessary to do anything further at the moment.
