### ISSUE TITLE
ComputeGenerators for dual mode

### ISSUE THREAD

**Issue by w-bruns** [Normaliz/Normaliz#66]
In order to get rid of the (twofold) GMP transition when computing the extreme rays in the inhomogeneous case, we could set up a version of Fourier-Motzkin that 

(1) avoids the start simplex or 

(2) -- perhaps easier -- computes the support hyperplanes of the start simplex by Fourier-Motzkin, avoiding the matrix inversion.

(1) has the advantage of avoiding any rank computation.

Moreover, we could allow a variant of the constructor of the full cone that avoids the rank test. It can be used when we have computed a coordinate transformation and know that the rank is correct. One could also think of avoiding the rank test altogether and check the rank when the start simplex is computed.

**Comment by w-bruns** [comment]
We could make the use of then start simplex depending on 

do_triangulation || do_partial_triangulation

This would save us an additional bool and would always work with -s.

**Comment by w-bruns** [comment]
Replace "use" by "computation of the support hyperplanes of".

**Comment by csoeger** [comment]
We added the dependency on do_(partial)_triangulation and removed the use of Bareiss for gmp. Furthermore we moved the make_prime before the the conversion from gmp back to long long.
