### ISSUE TITLE
Verbose output in dual mode

### ISSUE THREAD

**Issue by csoeger** [Normaliz/Normaliz#76]
The number of positive, neutral, and negative elements printed seem to be wrong in some cases, here a huge example with inhomogeneous input
```
Final sizes: Pos 27609516 Neg 1 Neutral 117912
==================================================
cut with halfspace 13 ...
Final sizes: Pos 0 Neg 0 Neutral 0
==================================================
cut with halfspace 14 ...
Final sizes: Pos 0 Neg 0 Neutral 6900
==================================================
cut with halfspace 15 ...
Final sizes: Pos 0 Neg 0 Neutral 0
Hilbert basis (truncated) 8120415
```
The number should not be zero, looks like the counters are not updated correctly.

**Comment by w-bruns** [comment]
Corrected

**Comment by w-bruns** [comment]
Korrigiert und im master abgesandt.

Winfried

Am 20.11.2015 um 17:06 schrieb Christof Soeger:
>
> The number of positive, neutral, and negative elements printed seem to 
> be wrong in some cases, here a huge example with inhomogeneous input
>
> |Final sizes: Pos 27609516 Neg 1 Neutral 117912 
> ================================================== cut with halfspace 
> 13 ... Final sizes: Pos 0 Neg 0 Neutral 0 
> ================================================== cut with halfspace 
> 14 ... Final sizes: Pos 0 Neg 0 Neutral 6900 
> ================================================== cut with halfspace 
> 15 ... Final sizes: Pos 0 Neg 0 Neutral 0 Hilbert basis (truncated) 
> 8120415 |
>
> The number should not be zero, looks like the counters are not updated 
> correctly.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/76>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/
