### ISSUE TITLE
Normality test

### ISSUE THREAD

**Issue by csoeger** [Normaliz/Normaliz#77]
We should introduce a possibility to just test whether the given monoid is normal (or integrally closed) or not. If it is, we still have to do the complete Hilbert basis computation. But if it is not, we can stop as soon as we find an element that is not reducible against the original generators. This especially helps if the product of support hyperplanes and Hilbert basis elements gets big (e.g. large binary graph models).

We can use the `ConeProperty::IsIntegrallyClosed` for this goal, currently it is just activating `HilbertBasis`.

Should we supply a witness for non-normality?

**Comment by w-bruns** [comment]
As a short option I propose -w for "witness", and we should provide one in the case of nonnormality. Otherwise we print the Hilbert basis.
