### ISSUE TITLE
inability to link to GMP at non-standard location, to build a shared library, etc

### ISSUE THREAD

**Issue by dimpase** [Normaliz/Normaliz#88]
- If you have GMP in a location unknown then the makefile cannot be used, and needs to be changed (http://trac.sagemath.org/ticket/18708#comment:12)
- one cannot build a shared library libnormaliz (something that would be needed to make a Python/Cython bindings to it)
- one cannot do "make install"

These things make support of normaliz in Sagemath flaky. If a good interface Sagemath is to be built, shared library support is a must. 

The easiest way to accomplish this would be to use autotools to provide a proper configure script, and all these missing abilites. Do you have any plans towards this?

**Comment by csoeger** [comment]
The suggested way to configure/compile is to use cmake, it offers all the points you mentioned. Please have a look at source/INSTALL for more details.

**Comment by w-bruns** [comment]
Dear Dima,

have you tried to compile libnormaliz using cmake (see Normaliz manual 
or INSTALL in source)? It finds GMP and offers the possibility to set 
various compile options. For example, it can build a shared library out 
of libnormaliz.

Winfried

Am 06.03.2016 um 15:56 schrieb Dmitrii Pasechnik:
>
>   * If you have GMP in a location unknown then the makefile cannot be
>     used, and needs to be changed
>     (http://trac.sagemath.org/ticket/18708#comment:12)
>   * one cannot build a shared library libnormaliz (something that
>     would be needed to make a Python/Cython bindings to it)
>   * one cannot do "make install"
>
> These things make support of normaliz in Sagemath flaky. If a good 
> interface Sagemath is to be built, shared library support is a must.
>
> The easiest way to accomplish this would be to use autotools to 
> provide a proper configure script, and all these missing abilites. Do 
> you have any plans towards this?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Normaliz/Normaliz/issues/88>.
>

-- 
Winfried Bruns   FB Mathematik/Informatik Universität Osnabrück
Albrechtstr, 28a 49074 Osnabrück Germany
Phone +49 541 969 2485 (office) +49 5405 5806 (private)
+49 173 376 4565 (mobile)
http://www.home.uni-osnabrueck.de/wbruns/

**Comment by dimpase** [comment]
I must say I had a look at p.8 of the manual, and it does not tell you that there are other places to look for details :-)

Anyhow, cmake's support in Sage is experimental, I'd prefer to do without, if possible (you don't want optional packages depend on experimental ones). One advantage of autotools over cmake is that one does not need any extra software for installing the package, all the bog-standard tools do the job.

Anyway, the current Sage functionality does not need normaliz's shared library, and hopefully the ticket I cited will get positively reviewed soon. As to going forward, we'll see.

**Comment by w-bruns** [comment]
Normaliz now has an autotools build system in addition to cmake. Will be distributed with version 3.1.2.
